### ISSUE TITLE
Cannot spawn on water

### ISSUE THREAD

**Issue by Project-Econome** [DayKoala/SakuraSpawners#1]
There is a bug where they cannot spawn onto of blocks on water my vommunity pointed this out because they make afk farms

**Comment by DayKoala** [comment]
Thanks, fixed in [#a518ade](https://github.com/DayKoala/SakuraSpawners/commit/a518adea7681e46515540bd9df301b088f6f188d) .

**Comment by Project-Econome** [comment]
Thank you!
