### ISSUE TITLE
Mobs dont spawn under spawner?

### ISSUE THREAD

**Issue by Project-Econome** [DayKoala/SakuraSpawners#2]
Apparently mobs only spawn onto of spawner and not both top and bottom you could solve this by making them spawn in air on the sides?

**Comment by DayKoala** [comment]
Hello, unfortunately this will not be possible, as it would cost more attempts for the Spawner to be able to define a valid location, thus consuming more process on your server, by default they can spawn a block above and a block below according to the position from the Spawner.

**Comment by Project-Econome** [comment]
Hmm why not make it using a ring method of points to spawn like hitboxes point outwards
